/* build.js — inlines styles.css and the ES modules into dist/calculator.html,
   then wraps that same HTML as a Framer code component.
   The deliverable makes zero network requests, so every asset must be inline. */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const src = join(root, 'src');
const out = join(root, 'dist', 'calculator.html');
const framerOut = join(root, 'dist', 'framer', 'PMICalculator.tsx');

// Every visitor lands on question 1, so start near the survey's own height: the
// page then loads at the right size and only grows once they ask for results.
const INITIAL_HEIGHT = 700;
// Framer's canvas placeholder, before the component reports its real height.
const INTRINSIC_HEIGHT = 1400;
const BASE64_LINE_LENGTH = 180;

// Dependency order: later modules may use earlier ones.
const MODULES = ['defaults.js', 'calc.js', 'survey.js', 'charts.js', 'ui.js'];

function flatten(name) {
  const source = readFileSync(join(src, name), 'utf8');
  return source
    // Drop the module graph: everything ends up in one scope.
    .replace(/^\s*import\s+[\s\S]*?\s+from\s+'[^']*';\s*$/gm, '')
    .replace(/^\s*export\s+\{[\s\S]*?\};\s*$/gm, '')
    .replace(/^(\s*)export\s+(?=(const|let|var|function|class|async)\b)/gm, '$1')
    .trim();
}

function assertNoNetwork(html) {
  const offenders = [
    [/<link\b(?![^>]*rel=["']?icon)/i, 'a <link> element'],
    [/<script[^>]+src=/i, 'an external <script src>'],
    [/@import\s/i, 'a CSS @import'],
    [/url\(\s*['"]?https?:/i, 'a remote url() in CSS'],
    [/https?:\/\/(?!www\.w3\.org)/i, 'an http(s) reference']
  ];
  for (const [pattern, description] of offenders) {
    const match = html.match(pattern);
    if (match) throw new Error(`Build refuses to ship ${description}: ${match[0]}`);
  }
}

/**
 * Wrap the built HTML as a Framer code component.
 *
 * The HTML is embedded base64-encoded rather than escaped into a template
 * literal. The inlined calculator script is itself full of template literals —
 * hundreds of backticks and `${` sequences — so escaping would mean a global
 * transform where a single missed sequence yields silently corrupt markup that
 * only shows up at runtime. Base64's alphabet is [A-Za-z0-9+/=], which cannot
 * collide with a string delimiter, an interpolation or a closing script tag.
 * The cost is a third more bytes and one decode when the component mounts.
 */
function buildFramerComponent(html) {
  const base64 = Buffer.from(html, 'utf8').toString('base64');
  const lines = base64.match(new RegExp(`.{1,${BASE64_LINE_LENGTH}}`, 'g')) || [];
  const chunks = lines.map((line) => `    "${line}",`).join('\n');

  return `// PMICalculator.tsx — generated by build.js. Edit src/, not this file.
//
// Framer code component wrapping the self-contained PMI admin cost calculator.
// Paste into Framer: Assets panel -> Code -> Create code file.

import { useEffect, useRef, useState } from "react"
import type { CSSProperties } from "react"

// The whole calculator document, base64 encoded. See build.js for why.
const HTML_BASE64 = [
${chunks}
].join("")

const INITIAL_HEIGHT = ${INITIAL_HEIGHT}

// Runs on mount only, so the server render never touches browser globals.
function decodeHtml(): string {
    if (typeof atob !== "function" || typeof TextDecoder !== "function") return ""
    const binary = atob(HTML_BASE64)
    const bytes = new Uint8Array(binary.length)
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
    return new TextDecoder("utf-8").decode(bytes)
}

/**
 * @framerDisableUnlink
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 * @framerIntrinsicWidth 1000
 * @framerIntrinsicHeight ${INTRINSIC_HEIGHT}
 */
export default function PMICalculator(props: { style?: CSSProperties }) {
    const iframeRef = useRef<HTMLIFrameElement>(null)
    const [html, setHtml] = useState("")
    const [height, setHeight] = useState(INITIAL_HEIGHT)

    useEffect(() => {
        setHtml(decodeHtml())
    }, [])

    useEffect(() => {
        function onMessage(event: MessageEvent) {
            const frame = iframeRef.current
            if (!frame || event.source !== frame.contentWindow) return
            if (!event.data || event.data.type !== "pmi-calc-height") return
            const next = Number(event.data.height)
            if (Number.isFinite(next) && next > 0) setHeight(next)
        }
        window.addEventListener("message", onMessage)
        return () => window.removeEventListener("message", onMessage)
    }, [])

    return (
        <div
            style={{
                width: "100%",
                ...props.style,
                position: "relative",
                height,
            }}
        >
            <iframe
                ref={iframeRef}
                srcDoc={html}
                title="PMI admin cost calculator"
                style={{
                    display: "block",
                    width: "100%",
                    height: "100%",
                    border: 0,
                }}
            />
        </div>
    )
}
`;
}

/** Framer rejects a code file that exports anything but the component. */
function assertSingleExport(tsx) {
  const exports = tsx.match(/^export\b/gm) || [];
  if (exports.length !== 1 || !/^export default function PMICalculator\b/m.test(tsx)) {
    throw new Error(`Framer component must have exactly one default export, found ${exports.length}`);
  }
  const imports = tsx.match(/^import .* from "([^"]+)"/gm) || [];
  for (const line of imports) {
    const from = line.match(/from "([^"]+)"/)[1];
    if (from !== 'react' && from !== 'framer') {
      throw new Error(`Framer component may only import from react or framer, found "${from}"`);
    }
  }
}

const css = readFileSync(join(src, 'styles.css'), 'utf8').trim();
const js = MODULES.map((name) => `/* ---- ${name} ---- */\n${flatten(name)}`).join('\n\n');

const html = readFileSync(join(src, 'index.html'), 'utf8')
  .replace('<link rel="stylesheet" href="styles.css">', `<style>\n${css}\n</style>`)
  .replace('<script type="module" src="ui.js"></script>', `<script>\n(function () {\n'use strict';\n${js}\n})();\n</script>`);

assertNoNetwork(html);

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, html, 'utf8');

const tsx = buildFramerComponent(html);
assertSingleExport(tsx);
mkdirSync(dirname(framerOut), { recursive: true });
writeFileSync(framerOut, tsx, 'utf8');

const kb = (bytes) => (bytes / 1024).toFixed(1);
process.stdout.write(`Built dist/calculator.html (${kb(Buffer.byteLength(html, 'utf8'))} kB)\n`);
process.stdout.write(`Built dist/framer/PMICalculator.tsx (${kb(Buffer.byteLength(tsx, 'utf8'))} kB)\n`);
